export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const PURCHASES_BURGER_SUCCESS = "PURCHASES_BURGER_SUCCESS"
export const PURCHASES_BURGER_START = 'PURCHASES_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'
export const FETCH_ORDER_INIT =' FETCH_ORDER_INIT'
export const FETCH_ORDER_SUCCESS =' FETCH_ORDER_SUCCESS'
